### ISSUE TITLE
LS_night.png error

### ISSUE THREAD

**Issue by Jeremy5909** [thewaytozion/widgets#2]
[Here](https://ibb.co/VLbrL6R) is an image. Im on ipad and its 6:22 PM if that is important.

**Comment by thewaytozion** [comment]
Run[Shortcut ](https://www.icloud.com/shortcuts/3f47d801765b417e9a6ade5c897b1aa4) from guideline point 1a

**Comment by Jeremy5909** [comment]
thanks
